# Generated by Selenium IDE
import openpyxl
import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from selenium.common.exceptions import NoSuchElementException


class FileExcelReader:
    file = ""
    sheetName = ""

    def __init__(self, file, sheetName):
        self.file = file
        self.sheetName = sheetName

    def getRowCount(self):
        wordbook = openpyxl.load_workbook(self.file)
        sheet = wordbook[self.sheetName]
        return (sheet.max_row)

    def getColumnCount(self):
        wordbook = openpyxl.load_workbook(self.file)
        sheet = wordbook[self.sheetName]
        return (sheet.max_column)

    def readData(self, rownum, colnum):
        wordbook = openpyxl.load_workbook(self.file)
        sheet = wordbook[self.sheetName]
        return sheet.cell(row=rownum, column=colnum).value

    def writeData(self, data, rownum, colnum):
        wordbook = openpyxl.load_workbook(self.file)
        sheet = wordbook[self.sheetName]
        sheet.cell(row=rownum, column=colnum).value = data
        wordbook.save(self.file)


class TestUpdateID():
    def setup_method(self):
        self.driver = webdriver.Chrome()
        self.driver.maximize_window()
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def first_step(self):
        self.driver.get('https://mybk.hcmut.edu.vn/stinfo/logout')
        self.driver.get(
            'https://sso.hcmut.edu.vn/cas/login?service=http%3A%2F%2Fmybk.hcmut.edu.vn%2Fstinfo%2F')

        self.driver.find_element(
            By.NAME, "username").send_keys("tan.lamcs1001")
        self.driver.find_element(By.NAME, "password").send_keys("lnt@H1720")
        self.driver.find_element(By.NAME, "submit").click()
        time.sleep(1)

    def test_updateID(self, id, place, date, expectedResult):
        self.driver.get("https://mybk.hcmut.edu.vn/stinfo/")
        time.sleep(3)
        self.driver.find_element(
            By.XPATH, '/html/body/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div/div[1]/a/div').click()
        time.sleep(10)

        self.driver.find_element(By.ID, "menu-cmnd-edit").click()
        time.sleep(5)
        idObj = self.driver.find_element(By.ID, "cmndEditCMND")
        placeObj = self.driver.find_element(By.ID, "cmndnoicapEditCMND")
        dateObj = self.driver.find_element(By.ID, "cmndngaycapEditCMND")

        idObj.click()
        idObj.send_keys(Keys.CONTROL + "a")
        idObj.send_keys(Keys.DELETE)

        placeObj.click()
        placeObj.send_keys(Keys.CONTROL + "a")
        placeObj.send_keys(Keys.DELETE)

        dateObj.click()
        dateObj.send_keys(Keys.CONTROL + "a")
        dateObj.send_keys(Keys.DELETE)

        idObj.send_keys(id)
        placeObj.send_keys(place)
        dateObj.send_keys(date)
        time.sleep(1)
        self.driver.find_element(By.ID, "btn_save_cmnd").click()
        time.sleep(7)
        if expectedResult == "Success":
            print(self.driver.find_element(
                By.CLASS_NAME, 'bootbox-body').text)
        elif expectedResult == "MissingIdValue":
            print(self.driver.find_element(
                By.XPATH, '//*[@id="editcmndForm"]/div[1]/div/div[3]/div[1]/div/ul/li').text)
        elif expectedResult == "MissingPlaceValue":
            print(self.driver.find_element(
                By.XPATH, '//*[@id="editcmndForm"]/div[1]/div/div[3]/div[2]/div/ul/li').text)
        elif expectedResult == "MissingDateValue":
            print(self.driver.find_element(
                By.XPATH, '//*[@id="editcmndForm"]/div[1]/div/div[3]/div[3]/div/ul/li').text)


if __name__ == "__main__":
    excel = FileExcelReader(
        'updateid_data.xlsx', "Sheet1")
    test = TestUpdateID()
    test.setup_method()
    test.first_step()
    nRows = excel.getRowCount()
    for row in range(2, nRows + 1):
        id = excel.readData(row, 1)
        place = excel.readData(row, 2)
        date = excel.readData(row, 3)
        expectedResult = excel.readData(row, 4)
        if id is None:
            id = ""
        if place is None:
            place = ""
        if date is None:
            date = ""
        print(id, date, place, expectedResult)
        try:
            result = test.test_updateID(id, place, date, expectedResult)
            excel.writeData("Passed", row, 5)
        except:
            print("error!")
            excel.writeData("Failed", row, 5)
    test.teardown_method()
